name: MineBlockScoreboard
main: org.flyingteam.mineblock.scoreboard.main
author: MineBlock Team.
description: MineBlock 计分板插件
version: 1.0
softdepend: [PlaceholderAPI]
commands:
  reloadscoreboard:
    permission: mineblock.scoreboard.command.reloadscoreboard
